### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by krische** [camptocamp/terraform-provider-puppetdb#6]
Is there any documentation of how to use this provider?

**Comment by cospeedster** [comment]
@krische Did you found something out? Or can you provide an example?

**Comment by krische** [comment]
@cospeedster No, I just gave up.

**Comment by cospeedster** [comment]
@krische Thanks for your response!

**Comment by raphink** [comment]
Just added some infos to the README https://github.com/camptocamp/terraform-provider-puppetdb/blob/master/README.md

**Comment by cospeedster** [comment]
@raphink Thank you for doing this. May you do this for terraform-provider-puppetca too?

**Comment by raphink** [comment]
I did it there, too :smile:
